
# [[main]]
#   identifier = "search"
#   name = "검색"
#   url = "/search/"
#   weight = 10
# [[main]]
#   identifier = "categories"
#   name = "카테고리"
#   url = "/categories/"
#   weight = 20
# [[main]]
#   identifier = "tags"
#   name = "태그"
#   url = "/tags/"
#   weight = 30
# [[main]]
#   identifier = "archives"
#   name = "연도"
#   url = "/archives/"
#   weight = 40
# [[main]]
#   identifier = "about"
#   name = "어바웃미"
#   url = "/about/"
#   weight = 50

# # social menu links

# [[social]]
#   name = "github"
#   type = "social"
#   weight = 1
#   url = "https://github.com/#"
# [[social]]
#   name = "twitter"
#   weight = 2
#   url = "https://twitter.com/#"
# [[social]]
#   name = "linkedin"
#   weight = 3
#   url = "https://www.linkedin.com/in/#"